pointcloud_map_path: "install/gae_launch/share/gae_launch/maps/shell_sim_map23/map.pcd"
pointcloud_map_metadata_path: "install/gae_launch/share/gae_launch/maps/shell_sim_map23/map_metadata.yaml"

map_projector_info_path: "install/gae_launch/share/gae_launch/maps/shell_sim_map23/map_projector_info.yaml"
lanelet2_map_path: "install/gae_launch/share/gae_launch/maps/shell_sim_map23/lane.osm"
