uint16 throttle         # Range: 0-100
uint16 steering         # Range: 0-3600
uint16 brake            # Range: 0-10000
uint8 mechanical_brake  # Range: 0-1 (0: off, 1: on)
uint8 gear              # Range: 0-2 (0: neutral, 1: drive, 2: reverse)
uint8 mode_auto         # Range: 0-1 (0: manual, 1: auto)
uint8 signal            # Range: 0-3 (0: off, 1: left, 2: right 3: stop)
uint8 brake_voltage     # Range: 0-10

